create table if not exists public.booking_availability_weekly (
  id bigint generated by default as identity primary key,
  weekday smallint not null check (weekday between 0 and 6),
  sort_order smallint not null default 0,
  start_time time not null,
  end_time time not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_availability_weekly_valid_window check (end_time > start_time),
  constraint booking_availability_weekly_unique unique (weekday, sort_order)
);

create table if not exists public.booking_availability_exceptions (
  id bigint generated by default as identity primary key,
  exception_date date not null,
  sort_order smallint not null default 0,
  mode text not null check (mode in ('closed','custom')),
  start_time time,
  end_time time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_availability_exceptions_window check (
    (mode = 'closed' and start_time is null and end_time is null)
    or
    (mode = 'custom' and start_time is not null and end_time is not null and end_time > start_time)
  ),
  constraint booking_availability_exceptions_unique unique (exception_date, sort_order)
);

alter table public.booking_availability_weekly enable row level security;
alter table public.booking_availability_exceptions enable row level security;

revoke all on public.booking_availability_weekly from anon;
revoke all on public.booking_availability_exceptions from anon;
grant select, insert, update, delete on public.booking_availability_weekly to authenticated;
grant select, insert, update, delete on public.booking_availability_exceptions to authenticated;
grant usage, select on sequence public.booking_availability_weekly_id_seq to authenticated;
grant usage, select on sequence public.booking_availability_exceptions_id_seq to authenticated;

create policy booking_availability_weekly_authenticated_select on public.booking_availability_weekly
for select to authenticated using (true);
create policy booking_availability_weekly_authenticated_insert on public.booking_availability_weekly
for insert to authenticated with check (true);
create policy booking_availability_weekly_authenticated_update on public.booking_availability_weekly
for update to authenticated using (true) with check (true);
create policy booking_availability_weekly_authenticated_delete on public.booking_availability_weekly
for delete to authenticated using (true);

create policy booking_availability_exceptions_authenticated_select on public.booking_availability_exceptions
for select to authenticated using (true);
create policy booking_availability_exceptions_authenticated_insert on public.booking_availability_exceptions
for insert to authenticated with check (true);
create policy booking_availability_exceptions_authenticated_update on public.booking_availability_exceptions
for update to authenticated using (true) with check (true);
create policy booking_availability_exceptions_authenticated_delete on public.booking_availability_exceptions
for delete to authenticated using (true);

insert into public.booking_availability_weekly (weekday, sort_order, start_time, end_time, enabled)
values
  (0,0,'09:00','16:00',true),
  (1,0,'09:00','16:00',true),
  (2,0,'09:00','13:00',true),
  (2,1,'17:00','21:00',true),
  (3,0,'09:00','16:00',true),
  (4,0,'09:00','15:00',true)
on conflict (weekday, sort_order) do update set
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  enabled = excluded.enabled,
  updated_at = now();
